[package]

name = "tunnelclient"
version = "0.1.0"
authors = [
    "Chris Macklin <chris.macklin@gmail.com>",
]
edition = "2018"

[[bin]]
name = "tunnelclient"

[dependencies]
piston_window = "0.118"
piston2d-graphics = "0.39"
pistoncore-glutin_window = "0.68"
piston2d-opengl_graphics = "0.77"
interpolation = "0.2"
yaml-rust = "0.4"
rmp-serde = "0.15"
serde = { version = "1", features = ["derive"] }
streaming-stats = "0.2"
simple-error = "0.2"
zmq = "0.9"
zero_configure = { path = "../zero_configure" }
regex = "1"
lazy_static = "1"
hostname = "0.3"
derive_more = "0.99"
log = "0.4"
simplelog = "0.10"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"
